---
session_store_driver: Directory
session_store_config: /etc/fdo/sessions/
ownership_voucher_store_driver: Directory
ownership_voucher_store_config: /etc/fdo/ownership_vouchers/
trusted_device_keys_path: /etc/fdo/keys/device_ca_cert.pem
owner_private_key_path: /etc/fdo/keys/owner_key.der
bind: 0.0.0.0:8081
service_info:
  rhsm_organization_id: 6454383
  rhsm_activation_key: SDOkey
  rhsm_run_insights: true
  sshkey_user: admin
  sshkey_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKtYhWvWR6mt7QFuIEIF0wHrASCru8JzkXLcROtSDOpe9FUd5kTj17nOYJL18uwjxZLgeBWQkyUccCNLQPd6/teYEtMfpgDTintS2eHRL/9nkE4enuCcgzMgdpGR3HQdF/fExB4/OC7/rAJS9doTxH2lJ7VLDMcMKDvWOIozcju0hczW/ADLed4tMi4XDrxjt9rell1cJCTV5Xrt74Ga+mmhH239XENMkGppIGvh6t2mfBl5Qx8CSIG3aMTbU6FkEqyWlTW6TkU6ukBNXal4oNcAs5EaW2MCh4S0J5+12XnEna9OzD23OTdYgcaQBBcDjHXcDAGm5hMLlHEF7yOP0rq5TS5aQSj3G8acNUnGWNlPtaULepuoXkOK51nJ4lfgTLodd3no6mJ9P2D+qMPLxCmHD6g7y48ZR27lamps4M8hJcA/OMeaGpOXuGiRXAmATLW1/ylUKydNRf6/Xanra1n4BgRQQuGRaU+SMkWH1NGnAA9UO7jRwRHSbI0tnPzyiiCyIsXW6biDZpBrvVh/VZzMPQovbGRtCmvEETzWrv255gjuBee2+pY0RYb2db7UqqegoVmPr/q8nO46VrTbBZuE+MTTqcw9igJTh+G9luz2lGVCUqpSf9GHUQjdwzX7t+a/UojONArmdj1pJA1bhpxzpdXeSMnNKBWOZVDoewVw== cardno:00050000843A"
