---
storage_driver: Directory
storage_config: /etc/fdo/rendezvous_registered/
session_store_driver: Directory
session_store_config: /etc/fdo/sessions/
trusted_manufacturer_keys_path: /etc/fdo/keys/manufacturer_cert.pem
bind: 0.0.0.0:8082
